#property strict
#property version   "0.4.0"
#property description "NodeTrade MT5 data/execution adapter. Live trading is OFF by default."
#include <Trade/Trade.mqh>

input string InpServerOrigin = "https://YOUR-NODETRADE-SERVER";
input string InpExpectedAccountID = "";
input string InpActivationCode = "";
input int InpBars = 300;
input int InpTimerSeconds = 5;
input int InpHTTPTimeoutMs = 5000;
input bool InpLiveTrading = false;
input double InpMaxVolume = 0.10;
input ulong InpMagic = 26090401;
input bool InpAllowLong = true;
input bool InpAllowShort = true;

CTrade trade;
datetime g_last_bar=0,g_day_marker=0,g_last_heartbeat=0,g_last_reconcile=0;
string g_session_token="",g_last_signal_key="";
double g_day_start_equity=0.0;

string AccountID(){return IntegerToString((long)AccountInfoInteger(ACCOUNT_LOGIN));}
string JsonEscape(const string value){string s=value;StringReplace(s,"\\","\\\\");StringReplace(s,"\"","\\\"");return s;}
string JsonNumber(const double value){return DoubleToString(value,10);}
string ExtractJsonString(const string json,const string key){string n="\""+key+"\":\"";int p=StringFind(json,n);if(p<0)return "";p+=StringLen(n);int e=StringFind(json,"\"",p);return e<0?"":StringSubstr(json,p,e-p);}
double ExtractJsonNumber(const string json,const string key,const double fallback=0.0){string n="\""+key+":";int p=StringFind(json,n);if(p<0)return fallback;p+=StringLen(n);int e=p,z=StringLen(json);while(e<z){ushort c=StringGetCharacter(json,e);if((c>='0'&&c<='9')||c=='-'||c=='+'||c=='.'||c=='e'||c=='E')e++;else break;}return e<=p?fallback:StringToDouble(StringSubstr(json,p,e-p));}

bool HttpPost(const string path,const string payload,const bool authenticated,string &response){char data[],result[];string result_headers="";string headers="Content-Type: application/json\r\nAccept: application/json\r\n";if(authenticated&&g_session_token!="")headers+="Authorization: Bearer "+g_session_token+"\r\n";int copied=StringToCharArray(payload,data,0,WHOLE_ARRAY,CP_UTF8);if(copied<=1)return false;copied--;ResetLastError();int status=WebRequest("POST",InpServerOrigin+path,headers,InpHTTPTimeoutMs,data,copied,result,result_headers);if(status==-1){PrintFormat("NodeTrade WebRequest failed path=%s error=%d",path,GetLastError());return false;}response=CharArrayToString(result,0,-1,CP_UTF8);if(status<200||status>=300){PrintFormat("NodeTrade HTTP status=%d path=%s",status,path);return false;}return true;}

bool Activate(){string body="{\"account_id\":\""+JsonEscape(AccountID())+"\",\"activation_key\":\""+JsonEscape(InpActivationCode)+"\"}";string response;if(!HttpPost("/v1/activate",body,false,response))return false;g_session_token=ExtractJsonString(response,"token");return g_session_token!="";}
void RefreshDayStart(){MqlDateTime n;TimeToStruct(TimeCurrent(),n);datetime marker=StructToTime(n)-n.hour*3600-n.min*60-n.sec;if(marker!=g_day_marker){g_day_marker=marker;g_day_start_equity=AccountInfoDouble(ACCOUNT_EQUITY);}if(g_day_start_equity<=0)g_day_start_equity=AccountInfoDouble(ACCOUNT_EQUITY);}

double NormalizeVolume(const double requested){double minv=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),maxv=MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),InpMaxVolume),step=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);if(step<=0||maxv<minv)return 0;double v=MathMax(minv,MathMin(maxv,requested));v=MathFloor(v/step+1e-9)*step;return v>=minv?NormalizeDouble(v,8):0;}
bool HasOurPosition(const ENUM_POSITION_TYPE type){for(int i=PositionsTotal()-1;i>=0;--i){ulong t=PositionGetTicket(i);if(t==0||!PositionSelectByTicket(t))continue;if(PositionGetString(POSITION_SYMBOL)!=_Symbol)continue;if((ulong)PositionGetInteger(POSITION_MAGIC)!=InpMagic)continue;if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE)==type)return true;}return false;}

string BuildRatesJson(const ENUM_TIMEFRAMES tf,const int count){MqlRates r[];ArraySetAsSeries(r,true);int n=CopyRates(_Symbol,tf,0,count,r);string out="[";for(int i=n-1;i>=0;--i){if(i<n-1)out+=",";double range=MathMax(0.0,r[i].high-r[i].low);double body=MathAbs(r[i].close-r[i].open);double upper=r[i].high-MathMax(r[i].open,r[i].close);double lower=MathMin(r[i].open,r[i].close)-r[i].low;out+="{\"time\":"+IntegerToString((long)r[i].time)+",\"open\":"+JsonNumber(r[i].open)+",\"high\":"+JsonNumber(r[i].high)+",\"low\":"+JsonNumber(r[i].low)+",\"close\":"+JsonNumber(r[i].close)+",\"tick_volume\":"+IntegerToString((long)r[i].tick_volume)+",\"real_volume\":"+IntegerToString((long)r[i].real_volume)+",\"range\":"+JsonNumber(range)+",\"body\":"+JsonNumber(body)+",\"upper_wick\":"+JsonNumber(upper)+",\"lower_wick\":"+JsonNumber(lower)+"}";}return out+"]";}

string BuildPositionsJson(){string out="[";bool first=true;for(int i=PositionsTotal()-1;i>=0;--i){ulong t=PositionGetTicket(i);if(t==0||!PositionSelectByTicket(t))continue;if(PositionGetString(POSITION_SYMBOL)!=_Symbol)continue;if(!first)out+=",";first=false;out+="{\"ticket\":"+IntegerToString((long)t)+",\"type\":"+IntegerToString((int)PositionGetInteger(POSITION_TYPE))+",\"volume\":"+JsonNumber(PositionGetDouble(POSITION_VOLUME))+",\"open_price\":"+JsonNumber(PositionGetDouble(POSITION_PRICE_OPEN))+",\"sl\":"+JsonNumber(PositionGetDouble(POSITION_SL))+",\"tp\":"+JsonNumber(PositionGetDouble(POSITION_TP))+",\"profit\":"+JsonNumber(PositionGetDouble(POSITION_PROFIT))+",\"swap\":"+JsonNumber(PositionGetDouble(POSITION_SWAP))+"}";}return out+"]";}
string BuildOrdersJson(){string out="[";bool first=true;for(int i=OrdersTotal()-1;i>=0;--i){ulong t=OrderGetTicket(i);if(t==0||!OrderSelect(t))continue;if(OrderGetString(ORDER_SYMBOL)!=_Symbol)continue;if(!first)out+=",";first=false;out+="{\"ticket\":"+IntegerToString((long)t)+",\"type\":"+IntegerToString((int)OrderGetInteger(ORDER_TYPE))+",\"volume\":"+JsonNumber(OrderGetDouble(ORDER_VOLUME_CURRENT))+",\"price\":"+JsonNumber(OrderGetDouble(ORDER_PRICE_OPEN))+",\"sl\":"+JsonNumber(OrderGetDouble(ORDER_SL))+",\"tp\":"+JsonNumber(OrderGetDouble(ORDER_TP))+"}";}return out+"]";}

string BuildSnapshot(const MqlTick &tick,const MqlRates &rates[]){int n=ArraySize(rates);double sh=0,sl=DBL_MAX;double atr=0;int atrn=MathMin(n-1,14);for(int i=0;i<n;i++){sh=MathMax(sh,rates[i].high);sl=MathMin(sl,rates[i].low);}for(int i=0;i<atrn;i++)atr+=rates[i].high-rates[i].low;if(atrn>0)atr/=atrn;double mid=(tick.bid+tick.ask)/2.0;double spread=tick.ask-tick.bid;double range=sh-sl;double trend=(range>0?(mid-sl)/range:0.5);string s="{\"account\":{\"login\":\""+JsonEscape(AccountID())+"\",\"balance\":"+JsonNumber(AccountInfoDouble(ACCOUNT_BALANCE))+",\"equity\":"+JsonNumber(AccountInfoDouble(ACCOUNT_EQUITY))+",\"free_margin\":"+JsonNumber(AccountInfoDouble(ACCOUNT_MARGIN_FREE))+",\"margin\":"+JsonNumber(AccountInfoDouble(ACCOUNT_MARGIN))+",\"margin_level\":"+JsonNumber(AccountInfoDouble(ACCOUNT_MARGIN_LEVEL))+",\"leverage\":"+IntegerToString((long)AccountInfoInteger(ACCOUNT_LEVERAGE))+",\"currency\":\""+JsonEscape(AccountInfoString(ACCOUNT_CURRENCY))+"\"},";
s+="\"symbol\":{\"name\":\""+JsonEscape(_Symbol)+"\",\"digits\":"+IntegerToString((int)SymbolInfoInteger(_Symbol,SYMBOL_DIGITS))+",\"point\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_POINT))+",\"tick_size\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE))+",\"tick_value\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE))+",\"contract_size\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_TRADE_CONTRACT_SIZE))+",\"volume_min\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN))+",\"volume_max\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX))+",\"volume_step\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP))+",\"stops_level\":"+IntegerToString((int)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_STOPS_LEVEL))+",\"freeze_level\":"+IntegerToString((int)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_FREEZE_LEVEL))+",\"filling_mode\":"+IntegerToString((int)SymbolInfoInteger(_Symbol,SYMBOL_FILLING_MODE))+",\"trade_mode\":"+IntegerToString((int)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_MODE))+"},";
s+="\"tick\":{\"time\":"+IntegerToString((long)tick.time)+",\"bid\":"+JsonNumber(tick.bid)+",\"ask\":"+JsonNumber(tick.ask)+",\"last\":"+JsonNumber(tick.last)+",\"volume\":"+IntegerToString((long)tick.volume)+",\"volume_real\":"+JsonNumber(tick.volume_real)+",\"spread\":"+JsonNumber(spread)+"},";
s+="\"market_structure\":{\"swing_high\":"+JsonNumber(sh)+",\"swing_low\":"+JsonNumber(sl)+",\"range\":"+JsonNumber(range)+",\"atr_proxy\":"+JsonNumber(atr)+",\"location_in_range\":"+JsonNumber(trend)+",\"regime_hint\":\""+(atr>0&&range>atr*8?"trend_or_breakout":"range_or_consolidation")+"\"},";
s+="\"positions\":"+BuildPositionsJson()+",\"pending_orders\":"+BuildOrdersJson()+",\"daily\":{\"start_equity\":"+JsonNumber(g_day_start_equity)+",\"pnl\":"+JsonNumber(AccountInfoDouble(ACCOUNT_EQUITY)-g_day_start_equity)+"}}";return s;}

bool Reconcile(){string body="{\"account_id\":\""+JsonEscape(AccountID())+"\",\"symbol\":\""+JsonEscape(_Symbol)+"\",\"positions\":"+BuildPositionsJson()+",\"pending_orders\":"+BuildOrdersJson()+",\"equity\":"+JsonNumber(AccountInfoDouble(ACCOUNT_EQUITY))+",\"balance\":"+JsonNumber(AccountInfoDouble(ACCOUNT_BALANCE))+",\"terminal_time\":"+IntegerToString((long)TimeCurrent())+"}";string response;if(!HttpPost("/v1/reconcile",body,true,response))return false;g_last_reconcile=TimeCurrent();return StringFind(response,"\"safe_to_trade\":false")<0;}
bool Heartbeat(){string body="{\"account_id\":\""+JsonEscape(AccountID())+"\",\"symbol\":\""+JsonEscape(_Symbol)+"\",\"terminal_time\":"+IntegerToString((long)TimeCurrent())+"}";string response;bool ok=HttpPost("/v1/heartbeat",body,true,response);if(ok)g_last_heartbeat=TimeCurrent();return ok;}

string BuildAnalyzeRequest(const MqlRates &rates[],const MqlTick &tick){string body="{\"account_id\":\""+JsonEscape(AccountID())+"\",\"symbol\":\""+JsonEscape(_Symbol)+"\",\"bid\":"+JsonNumber(tick.bid)+",\"ask\":"+JsonNumber(tick.ask)+",\"equity\":"+JsonNumber(AccountInfoDouble(ACCOUNT_EQUITY))+",\"day_start_equity\":"+JsonNumber(g_day_start_equity)+",\"tick_size\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_SIZE))+",\"tick_value\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_TRADE_TICK_VALUE))+",\"volume_min\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN))+",\"volume_max\":"+JsonNumber(MathMin(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),InpMaxVolume)) +",\"volume_step\":"+JsonNumber(SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP))+",\"candles\":[";int total=ArraySize(rates);for(int i=total-1;i>=0;--i){if(i<total-1)body+=",";body+="{\"time\":"+IntegerToString((long)rates[i].time)+",\"open\":"+JsonNumber(rates[i].open)+",\"high\":"+JsonNumber(rates[i].high)+",\"low\":"+JsonNumber(rates[i].low)+",\"close\":"+JsonNumber(rates[i].close)+",\"volume\":"+JsonNumber((double)rates[i].tick_volume)+"}";}body+="] ,\"snapshot\":"+BuildSnapshot(tick,rates)+",\"multi_timeframe\":{\"M5\":"+BuildRatesJson(PERIOD_M5,100)+",\"M15\":"+BuildRatesJson(PERIOD_M15,100)+",\"H1\":"+BuildRatesJson(PERIOD_H1,100)+",\"H4\":"+BuildRatesJson(PERIOD_H4,100)+"}}";return body;}

bool ExecuteSignal(const string action,const double volume,const double stop,const double target,const string signal_key){if(!InpLiveTrading||action=="wait")return true;if(signal_key==""||signal_key==g_last_signal_key)return true;double v=NormalizeVolume(volume);if(v<=0||stop<=0||target<=0)return false;trade.SetExpertMagicNumber(InpMagic);trade.SetTypeFillingBySymbol(_Symbol);trade.SetAsyncMode(false);bool sent=false;if(action=="long"&&InpAllowLong&&!HasOurPosition(POSITION_TYPE_BUY))sent=trade.Buy(v,_Symbol,0,stop,target,"NodeTrade");else if(action=="short"&&InpAllowShort&&!HasOurPosition(POSITION_TYPE_SELL))sent=trade.Sell(v,_Symbol,0,stop,target,"NodeTrade");else return true;uint rc=trade.ResultRetcode();if(!sent||(rc!=TRADE_RETCODE_DONE&&rc!=TRADE_RETCODE_DONE_PARTIAL&&rc!=TRADE_RETCODE_PLACED)){PrintFormat("NodeTrade order rejected retcode=%u description=%s",rc,trade.ResultRetcodeDescription());return false;}g_last_signal_key=signal_key;return true;}

void PollNodeTrade(){RefreshDayStart();if(g_session_token==""&&!Activate())return;if(TimeCurrent()-g_last_heartbeat>=30&&!Heartbeat()){g_session_token="";return;}if(TimeCurrent()-g_last_reconcile>=60&&!Reconcile())return;MqlRates rates[];ArraySetAsSeries(rates,true);int copied=CopyRates(_Symbol,PERIOD_CURRENT,0,InpBars,rates);if(copied<100)return;MqlTick tick;if(!SymbolInfoTick(_Symbol,tick)||tick.bid<=0||tick.ask<=0||tick.ask<tick.bid)return;if(rates[0].time==g_last_bar)return;g_last_bar=rates[0].time;string response;if(!HttpPost("/v1/analyze",BuildAnalyzeRequest(rates,tick),true,response))return;string action=ExtractJsonString(response,"action"),request_id=ExtractJsonString(response,"request_id");double stop=ExtractJsonNumber(response,"stop"),target=ExtractJsonNumber(response,"target"),volume=ExtractJsonNumber(response,"volume");PrintFormat("NodeTrade signal symbol=%s action=%s volume=%.8f stop=%.5f target=%.5f request=%s",_Symbol,action,volume,stop,target,request_id);if(action=="long"||action=="short")ExecuteSignal(action,volume,stop,target,request_id);}

int OnInit(){if(InpServerOrigin==""||InpActivationCode=="")return INIT_PARAMETERS_INCORRECT;string actual=AccountID();if(InpExpectedAccountID!=""&&InpExpectedAccountID!=actual)return INIT_PARAMETERS_INCORRECT;RefreshDayStart();if(!Activate())return INIT_FAILED;if(!Reconcile())return INIT_FAILED;trade.SetExpertMagicNumber(InpMagic);EventSetTimer(MathMax(1,InpTimerSeconds));Print("NodeTrade EA initialized. Live trading default is OFF.");return INIT_SUCCEEDED;}
void OnDeinit(const int reason){EventKillTimer();}
void OnTimer(){PollNodeTrade();}
void OnTick(){}
void OnTradeTransaction(const MqlTradeTransaction &trans,const MqlTradeRequest &request,const MqlTradeResult &result){if(trans.symbol!=_Symbol||g_session_token=="")return;string event_key=IntegerToString((long)trans.deal)+":"+IntegerToString((long)trans.order)+":"+IntegerToString((int)trans.type)+":"+IntegerToString((long)trans.position);double profit=0.0,commission=0.0,swap=0.0;if(trans.deal>0&&HistoryDealSelect(trans.deal)){profit=HistoryDealGetDouble(trans.deal,DEAL_PROFIT);commission=HistoryDealGetDouble(trans.deal,DEAL_COMMISSION);swap=HistoryDealGetDouble(trans.deal,DEAL_SWAP);}string body="{\"account_id\":\""+JsonEscape(AccountID())+"\",\"event_id\":\""+JsonEscape(event_key)+"\",\"symbol\":\""+JsonEscape(trans.symbol)+"\",\"event_type\":\""+IntegerToString((int)trans.type)+"\",\"ticket\":"+IntegerToString((long)trans.position)+",\"deal\":"+IntegerToString((long)trans.deal)+",\"order\":"+IntegerToString((long)trans.order)+",\"volume\":"+JsonNumber(trans.volume)+",\"price\":"+JsonNumber(trans.price)+",\"profit\":"+JsonNumber(profit)+",\"commission\":"+JsonNumber(commission)+",\"swap\":"+JsonNumber(swap)+",\"time\":"+IntegerToString((long)trans.time)+",\"payload\":{\"retcode\":"+IntegerToString((int)result.retcode)+"}}";string response;HttpPost("/v1/trade-events",body,true,response);}
